# Generated by Django 5.0 on 2023-12-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_auto_20191010_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monto_Inicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoinicial', models.FloatField()),
            ],
        ),
    ]
