# Generated by Django 5.0 on 2023-12-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_monto_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monto_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montofinal', models.FloatField()),
            ],
        ),
    ]
