# Generated by Django 5.0 on 2023-12-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_monto_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameimpuesto', models.CharField(max_length=64)),
                ('montopagar', models.FloatField()),
            ],
        ),
    ]
